# Install required software for compiling Redis from source
#
- name: Install required tools for compiling Redis
  dnf:
    name: [gcc, make, systemd-devel, tar]
    state: latest
  tags: [redis]



# Download and unpack source code for building Redis.
# Easiest method it to download it from Redis download page:
# https://redis.io/download
#
- name: Download Redis source files
  get_url:
    dest: "{{ redis_sources_path }}"
    url: "http://download.redis.io/releases/redis-{{ redis_version }}.tar.gz"
  tags: [redis]

- name: Unpack downloaded Redis sources
  unarchive:
    src: "{{ redis_sources_path }}/redis-{{ redis_version }}.tar.gz"
    dest: "{{ redis_sources_path }}"
    owner: "{{ redis_build_user }}"
    group: "{{ redis_build_group }}"
    copy: no
    creates: "{{ redis_sources_path }}/redis-{{ redis_version }}"
  tags: [redis]



# Compile and install Redis
# It will be compiled by using different user than root.
#
- name: Compile Redis
  command: make MALLOC=libc
  args:
    chdir: "{{ redis_sources_path }}/redis-{{ redis_version }}"
  become: true
  become_user: "{{ redis_build_user }}"
  tags: [redis]

- name: Make sure that Redis installation directory exists
  file:
    path: "{{ redis_install_path }}/bin"
    state: directory
    mode: 0755
    owner: root
    group: root
  tags: [redis]

- name: Copy compiled binaries to installation directory
  copy:
    src: "{{ redis_sources_path }}/redis-{{ redis_version }}/src/{{ item }}"
    dest: "{{ redis_install_path }}/bin"
    remote_src: yes
    owner: root
    group: root
    mode: 0755
  with_items:
    - redis-benchmark
    - redis-check-aof
    - redis-check-rdb
    - redis-cli
    - redis-server
  tags: [redis]

- name: Copy redis.conf file from sources to installation path
  copy:
    src: "{{ redis_sources_path }}/redis-{{ redis_version }}/redis.conf"
    dest: "{{ redis_install_path }}"
    remote_src: yes
    owner: root
    group: root
    mode: 0644
  tags: [redis]



# Remove downloaded sources after installation
#
- name: Cleanup files after installation
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ redis_sources_path }}/redis-{{ redis_version }}.tar.gz"
    - "{{ redis_sources_path }}/redis-{{ redis_version }}"
  tags: [redis]
