# Install/Update Redis to desired version
# These tasks will be executed when
#  1. Redis is not installed from within this role
#  2. Redis is installed but not in desired version
#
- name: Check if Redis is installed in required version
  shell: "{{ redis_install_path }}/bin/redis-cli --version | awk '{print $2}'"
  ignore_errors: yes
  changed_when: false
  register: redis_version_test
  tags: [redis]

- include_tasks: install.yml
  when: "redis_version_test.stdout != redis_version"
  tags: [redis]



# Configure redis
#
- import_tasks: configure.yml



# Make sure that redis service is started and enabled on boot
#
- name: Start and enable Redis service
  service:
    name: redis
    state: started
    enabled: yes
  tags: [redis]
