# Install/Update nginx to desired version
# These tasks will be executed when
#  1. nginx is not installed from within this role
#  2. nginx is installed but not in desired version
#
- name: Check if nginx is installed in required version
  shell: "{{ nginx_install_path }}/sbin/nginx -v 2>&1 | awk '{print substr($3, 7)}'"
  args:
    warn: no
  ignore_errors: yes
  changed_when: false
  register: nginx_version_test
  tags: [nginx]

- include_tasks: install.yml
  when: "nginx_version_test.stdout != nginx_version"
  tags: [nginx]



# Make sure that libselinux-python is installed (required for Ansible templates)
#
- name: Make sure that libselinux-python is installed
  yum:
    name: libselinux-python
    state: latest
  tags: [nginx]



# Install/Update nginx to desired version
# These tasks will be executed when
#  1. nginx is not installed
#  2. nginx is installed but not in desired version
#
- include: install.yml
  when: "nginx_install_new_version == true and nginx_manage_installation == true"



# Configure nginx
#
- include: configure.yml
  when: "nginx_manage_configuration == true"



# Configure nginx servers
#
- include: servers.yml
  when: "nginx_manage_servers == true"



# Make sure that nginx service is started and enabled on boot
#
- name: Start and enable nginx service
  service:
    name: nginx
    state: started
    enabled: yes
  tags: [nginx, healthcheck]
