# Install/Update nginx to desired version
# These tasks will be executed when
#  1. nginx is not installed from within this role
#  2. nginx is installed but not in desired version
#
- name: Check if nginx is installed in required version
  shell: "{{ nginx_install_path }}/sbin/nginx -v 2>&1 | awk '{print substr($3, 7)}'"
  ignore_errors: yes
  changed_when: false
  register: nginx_version_test
  tags: [nginx]

- include_tasks: install.yml
  when: "nginx_version_test.stdout != nginx_version"
  tags: [nginx]



# Create groups, users and add basic configuration
#
- import_tasks: configure.yml



# Make sure that nginx service is started and enabled on boot
#
- name: Start and enable nginx service
  service:
    name: nginx
    state: started
    enabled: yes
  tags: [nginx, healthcheck]
