# Create directories for MongoDB
#
- name: Create directories for MongoDB
  file:
    path: "{{ item }}"
    state: directory
    owner: mongod
    group: mongod
    mode: 0755
  with_items:
    - /var/lib/mongo
    - /var/log/mongodb
    - /var/run/mongodb
  tags: [ mongodb ]



# Update /etc/hosts file for local databases
#
- name: Setup /etc/hosts file
  lineinfile:
    path: /etc/hosts
    line: "127.0.0.1 {{ mongodb_host }}"
    state: present
  when: "mongodb_is_local == true"
  tags: [ mongodb ]



# Enable auto-restart for mongod in case of failure
#
- name: Ensure override directory exists for mongod service
  ansible.builtin.file:
    path: /etc/systemd/system/mongod.service.d
    state: directory
    mode: 0755
  tags: [mongodb]

- name: Add restart block to mongod service
  ansible.builtin.copy:
    dest: /etc/systemd/system/mongod.service.d/override.conf
    content: |
      [Service]
      Restart=on-failure
      RestartSec=10
    mode: 0644
  notify: Reload systemctl daemon
  tags: [mongodb]


# Turn on authorization
#
- name: Enable security section
  lineinfile:
    path: "{{ mongodb_config_file }}"
    line: "security:"
    state: present
    regexp: '^#?security'
  notify: restart mongod
  tags: [ mongodb ]

- name: Enable authorization
  lineinfile:
    dest: "{{ mongodb_config_file }}"
    line: "  authorization: enabled"
    state: present
    regexp: '^[ \t]+authorization'
    insertafter: "security:"
  notify: restart mongod
  tags: [ mongodb ]



# Configure network section
#
- name: Enable network interfaces section
  lineinfile:
    path: "{{ mongodb_config_file }}"
    line: "net:"
    state: present
    regexp: '^#?net'
  notify: restart mongod
  tags: [ mongodb ]

- name: Set server IP address
  lineinfile:
    dest: "{{ mongodb_config_file }}"
    line: "  bindIp: {{ mongodb_host }}"
    state: present
    regexp: '^[ \t]+bindIp'
    insertafter: "net:"
  notify: restart mongod
  tags: [ mongodb ]

- name: Add TLS configuration section
  blockinfile:
    block: |
      net:
        tls:
          mode: requireTLS
          certificateKeyFile: /var/lib/mongo/tls/mongo.pem
          CAFile: /var/lib/mongo/tls/server-ca.crt
          disabledProtocols: TLS1_0,TLS1_1,TLS1_2
    marker: '# {mark} Ansible managed block for TLS configuration'
    path: "{{ mongodb_config_file }}"
  notify: restart mongod
  tags: [ mongodb ]
