# Create directories for MongoDB
#
- name: Create directories for MongoDB
  file:
    path: "{{ item }}"
    state: directory
    owner: mongod
    group: mongod
    mode: 0755
  with_items:
    - /var/lib/mongo
    - /var/log/mongodb
    - /var/run/mongodb
  tags: [ mongodb ]



# Update /etc/hosts file for local databases
#
- name: Setup /etc/hosts file
  lineinfile:
    path: /etc/hosts
    line: "127.0.0.1 {{ mongodb_host }}"
    state: present
  when: "mongodb_is_local == true"
  tags: [ mongodb ]



# Turn on authorization
#
- name: Enable security section
  lineinfile:
    path: "{{ mongodb_config_file }}"
    line: "security:"
    state: present
    regexp: '^#?security'
  notify: restart mongod
  tags: [ mongodb ]

- name: Enable authorization
  lineinfile:
    dest: "{{ mongodb_config_file }}"
    line: "  authorization: enabled"
    state: present
    regexp: '^[ \t]+authorization'
    insertafter: "security:"
  notify: restart mongod
  tags: [ mongodb ]



# Configure network section
#
- name: Enable network interfaces section
  lineinfile:
    path: "{{ mongodb_config_file }}"
    line: "net:"
    state: present
    regexp: '^#?net'
  notify: restart mongod
  tags: [ mongodb ]

- name: Set server IP address
  lineinfile:
    dest: "{{ mongodb_config_file }}"
    line: "  bindIp: {{ mongodb_host }}"
    state: present
    regexp: '^[ \t]+bindIp'
    insertafter: "net:"
  notify: restart mongod
  tags: [ mongodb ]

- name: Add TLS configuration section
  blockinfile:
    block: |
      net:
        tls:
          mode: requireTLS
          certificateKeyFile: /var/lib/mongo/tls/mongo.pem
          disabledProtocols: TLS1_0,TLS1_1
    marker: '# {mark} Ansible managed block for TLS configuration'
    path: "{{ mongodb_config_file }}"
  notify: restart mongod
  tags: [ mongodb ]
