# Install MongoDB
#
- name: Check MongoDB version
  shell: mongod --version | head -n1 | awk '{print substr($3, 2)}'
  register: mongodb_version_test
  ignore_errors: yes
  changed_when: false
  tags: [ mongodb ]

- include_tasks: install.yml
  when: "mongodb_version_test.stdout != mongodb_version"
  tags: [ mongodb ]



# Configure MongoDB, manage users, databases and backups
#
- import_tasks: pymongo.yml
- import_tasks: tls.yml
- import_tasks: configure.yml
- import_tasks: admin.yml
- import_tasks: admin-commands.yml
- import_tasks: users.yml
- import_tasks: backup.yml



# Make sure that mongod service is started and enabled on boot
#
- name: Start and enable MongoDB service
  service:
    name: mongod
    state: started
    enabled: yes
  tags: [ mongodb ]
