# Ensure that pymongo and cryptography are installed to successfully execute tasks in this role
#
- name: Install pip command
  ansible.builtin.dnf:
    name: python3.12-pip
    state: latest
  tags: [mongodb]

- name: Install required Python libraries
  pip:
    name: "{{ item }}"
    state: latest
  with_items:
    - pymongo
    - cryptography
    - pyopenssl
  tags: [ mongodb ]
