# Create databases with users
# Each database should have separate user
#
- name: Create databases and users
  mongodb_user:
    database: "{{ item.key }}"
    login_host: "{{ mongodb_host }}"
    login_password: "{{ mongodb_admin_password }}"
    login_user: admin
    name: "{{ item.value.user }}"
    password: "{{ item.value.password }}"
    roles: "{{ item.value.roles }}"
    update_password: on_create
    ssl: true
    ssl_ca_certs: /var/lib/mongo/tls/server-ca.crt
  with_dict: "{{ mongodb_databases }}"
  no_log: true
  tags: [ mongodb ]
