# Version of MySQL that should be installed
mysql_version: "8.0.20"

# MySQL root password
mysql_root_password: "rKp#rX3EP?Y2JGug*q,s>F,)@Hbuf9KCH#Z8odF44!)vH7MmrwJ3"

# MySQL root login host
mysql_root_host: 127.0.0.1

# Path to configuration file
mysql_config_file: "/etc/my.cnf"

# List of default secure config options for /etc/ssh/sshd_config file
mysql_default_configuration:
  log-error: "/var/log/mysqld.log"
  slow_query_log: "1"
  slow_query_log_file: "/var/lib/mysql/slow-query.log"
  long_query_time: "5"
  skip-name-resolve: "1"

# Custom user settings to be applied to {{ mysql_config_file }} file. Please refer to README.md in this role how to use it
mysql_user_configuration: []

# List of users that should be added to mysql group in order to access log files
mysql_group_users:
  - developer

# List of databases that should be created. Each database should have separate user
mysql_databases:
  example:
    user: example
    passowrd: "+;GPS,uP6%MXYTFo2k8bpo57v"
    host: "127.0.0.1"

####### CHOOSE IF THIS ROLE SHOULD EXECUTE TASKS FROM GIVEN GROUPS #######

# Should this role perform databases backups?
mysql_manage_backup: yes





####### BACKUP TASKS CONFIGURATION #######

# Name of the user that will perform backups
mysql_backup_user: backup

# Password for mysql backup user
mysql_backup_user_password: "J2AW9oRZT?wO@C^S1!Qxsq03d8r"

# List of database to backup
# Here is full example with all options:
#
# mysql_backup_databases:
#  - {
#    database: example, # database name to backup
#    backup_directory: /var/www/example.com/db, # directory for storing backups
#    backup_directory_owner: developer, # directory owner
#    backup_directory_group: developer, # directory group
#    rotate: 30, # number of files to rotate
#    backup_frequency: daily, # how often should backups be performed (daily, weekly, etc)
#    s3_bucket: mysql-backup # name of the s3 bucket that backup should be pushed through. it requires having awscli up and running
# }
mysql_backup_databases:
 - {
    database: example,
    backup_directory: /var/db,
    backup_directory_owner: root,
    backup_directory_group: root,
    rotate: 30,
    backup_frequency: daily
 }
