# Version of MySQL that should be installed
mysql_version: "8.0.20"

# MySQL root password
mysql_root_password: "rKp#rX3EP?Y2JGug*q,s>F,)@Hbuf9KCH#Z8odF44!)vH7MmrwJ4"

# MySQL root login host
mysql_root_host: 127.0.0.1

# Path to configuration file
mysql_config_file: "/etc/my.cnf"

# List of default secure config options for /etc/ssh/sshd_config file
mysql_default_configuration:
  log-error: "/var/log/mysqld.log"
  slow_query_log: "1"
  slow_query_log_file: "/var/lib/mysql/slow-query.log"
  long_query_time: "5"
  skip-name-resolve: "1"
  ssl-ca: "ca.pem"
  ssl-cert: "server-cert.pem"
  ssl-key: "server-key.pem"
  tls_version: "TLSv1.3"
  require_secure_transport: "1"
  bind-address: "0.0.0.0"

# Custom user settings to be applied to {{ mysql_config_file }} file. Please refer to README.md in this role how to use it
mysql_user_configuration: []

# List of users that should be added to mysql group in order to access log files
mysql_group_users:
  - developer

# List of databases that should be created. Each database should have separate user
mysql_databases:
  example:
    user: example
    passowrd: "+;GPS,uP6%MXYTFo2k8bpo57v"
    host: "127.0.0.1"
    backup: yes

# Name of the user for backups
mysql_backup_user: backup

# Password for mysql backup user
mysql_backup_user_password: "J2AW9oRZT?wO@C^S1!Qxsq03d8r"
