# Restart MongoDB mongod service
# This handler is executed on changes in MongoDB configuration file
#
- name: restart mongod
  service:
    name: mongod
    state: restarted

- name: Reload systemctl daemon
  ansible.builtin.systemd_service:
    daemon_reload: true
