# Install or update AWS CLI to required version
# This task will be executed if AWS CLI is not installed or it's installed in different version
#
- name: Check if AWS CLI is installed in required version
  shell: /usr/local/bin/aws --version | awk -F'/' '{print $2}' | awk '{print $1}'
  args:
    warn: no
  ignore_errors: yes
  changed_when: false
  register: awscli_version_test
  tags: [awscli]

- include_tasks: install.yml
  when: "awscli_version_test.stdout != awscli_version"
  tags: [awscli]

# Import remaining tasks
#
- import_tasks: configure.yml
