# Node.js has it's own repository. In order to have it available we need to add it to Yum repositories
#
- name: Make sure that Node.js repository is available
  template:
    src: nodesource-el9.repo.j2
    dest: /etc/yum.repos.d/nodesource-el9.repo
    owner: root
    group: root
    mode: 0644
  tags: [nodejs]



# Import RPM key
#
- name: Import NodeSource RPM key
  ansible.builtin.rpm_key:
    key: https://rpm.nodesource.com/gpgkey/ns-operations-public.key
    state: present
  tags: [nodejs]



# Install Node.js and NPM
#
- name: Install Node.js and NPM
  dnf:
    name: "nodejs-{{ nodejs_version }}"
    state: latest
    disablerepo: appstream
  tags: [nodejs]
