# Configure /etc/ssh/sshd_config file options and host keys
#
- name: Merge default and user config
  set_fact:
    ssh_sshd_config: "{{ ssh_sshd_default_config_options | combine(ssh_sshd_user_config_options) }}"
  tags: [ ssh ]

- name: Add a file with additional sshd rules
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config.d/25-ansible.conf
    owner: root
    group: root
    mode: 0600
  tags: [ ssh ]

- name: Ensure that sshd includes additional configs
  lineinfile:
    path: /etc/ssh/sshd_config
    line: "Include /etc/ssh/sshd_config.d/*.conf"
    state: present
  notify: restart sshd
  tags: [ ssh ]

- name: Enable HostKeys in /etc/ssh/sshd_config
  lineinfile:
    path: /etc/ssh/sshd_config
    line: "HostKey /etc/ssh/{{ item }}"
    state: present
  with_items: "{{ ssh_sshd_host_keys }}"
  notify: restart sshd
  tags: [ ssh ]

- name: Disable all other HostKeys in /etc/ssh/sshd_config
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "HostKey /etc/ssh/(?!{{ ssh_sshd_host_keys | join('|') }})"
    state: absent
  notify: restart sshd
  tags: [ ssh ]



# Make sure that the sshd service is started and enabled on boot
#
- name: Make sure that the sshd service is started and enabled on boot
  service:
    name: sshd
    state: started
    enabled: yes
  tags: [ ssh ]
