# Create databases in MySQL database with user that has access to the database
#
- name: Create databases
  mysql_db:
    name: "{{ item.key }}"
    state: present
    login_host: "{{ mysql_root_host }}"
  no_log: true
  with_dict: "{{ mysql_databases }}"
  tags: [ mysql ]

- name: Create users and assign them to databases
  community.mysql.mysql_user:
    name: "{{ item.value.user }}"
    plugin: caching_sha2_password
    plugin_auth_string: "{{ item.value.password }}"
    salt: "{{ item.value.salt }}"
    host: "{{ item.value.host }}"
    priv: "{{ item.key }}.*:ALL"
    login_host: "{{ mysql_root_host }}"
    tls_requires: "{{ item.value.tls_requires | default({}) }}"
  with_dict: "{{ mysql_databases }}"
  no_log: yes
  tags: [mysql]
