# Create databases in MySQL database with user that has access to the database
#
- name: Create databases
  mysql_db:
    name: "{{ item.key }}"
    state: present
  with_dict: "{{ mysql_databases }}"
  tags: [mysql]

- name: Create users and assign them to databases
  mysql_user:
    name: "{{ item.value.user }}"
    password: "{{ item.value.password }}"
    host: "{{ item.value.host }}"
    priv: "{{ item.key }}.*:ALL"
  with_dict: "{{ mysql_databases }}"
  no_log: yes
  tags: [mysql]



# Enable require x509 for given users
#
- set_fact:
    mysql_users_with_x509: "{{ mysql_backup_databases|default([]) + [item] }}"
  with_dict: "{{ mysql_databases }}"
  when: "item.value.requireX509 | default(false) == true"
  no_log: yes
  tags: [mysql]

- name: Require x509 connection for selected users
  shell: "/usr/bin/mysql --execute 'ALTER USER '{{ item.value.user }}'@'{{ item.value.host }}' REQUIRE X509; FLUSH PRIVILEGES;'"
  with_items: "{{ mysql_users_with_x509 }}"
  changed_when: false
  when: "mysql_users_with_x509 is defined"
  no_log: yes
  tags: [mysql]
