# Create databases in MySQL database with user that has access to the database
#
- name: Create databases
  mysql_db:
    name: "{{ item.key }}"
    state: present
  with_dict: "{{ mysql_databases }}"
  tags: [mysql]

- name: Create users and assign them to databases
  mysql_user:
    name: "{{ item.value.user }}"
    password: "{{ item.value.password }}"
    priv: "{{ item.key }}.*:ALL"
  with_dict: "{{ mysql_databases }}"
  no_log: yes
  tags: [mysql]
