# Install MySQL RPM from remote repository
#
- name: Import RPM key
  rpm_key:
    key: https://repo.mysql.com/RPM-GPG-KEY-mysql-2022
    state: present
  tags: [mysql]

- name: Install MySQL RPM
  dnf:
    name: "https://dev.mysql.com/get/mysql80-community-release-el9-1.noarch.rpm"
    state: latest
  tags: [mysql]



# Install MySQL packages
#
- name: Install MySQL community server
  dnf:
    name: "mysql-community-server-{{ mysql_version }}"
    state: latest
    disablerepo: appstream
  tags: [mysql]
