# Install or update MySQL server to required version
# This task will be executed if MySQL is not installed or it's installed in different version
#
- name: Check if MySQL is installed in required version
  shell: mysql --version | awk '{print $3}'
  args:
    warn: no
  ignore_errors: yes
  changed_when: false
  register: mysql_version_test
  tags: [mysql]

- include: install.yml
  when: "mysql_version_test.stdout != mysql_version"



# Make sure that MySQL server service is started and enabled on boot
#
- name: Start and enable MySQL server service
  service:
    name: mysqld
    state: started
    enabled: yes
  tags: [mysql]



# Manage tools, databases, accounts and backups
#
- import_tasks: root-password.yml



# Configure MySQL server
#
- include: configure.yml
  when: "mysql_manage_configuration == true"



# Setup databases and database users
#
- include: databases.yml
  when: "mysql_manage_databases_and_users == true"


# Install MySQLTuner tool
#
- include: mysqltuner.yml
  when: "mysql_install_mysqltuner == true"



# Setup backup script
#
- include: backup.yml
  when: "mysql_manage_backup == true"
