# Install or update MySQL server to required version
# This task will be executed if MySQL is not installed or it's installed in different version
#
- name: Check if MySQL is installed in required version
  shell: mysqld --version | awk '{print $3}'
  ignore_errors: yes
  changed_when: false
  register: mysql_version_test
  tags: [ mysql ]

- include_tasks: install.yml
  when: "mysql_version_test.stdout != mysql_version"
  tags: [ mysql ]



# Make sure that MySQL server service is started and enabled on boot
#
- name: Start and enable MySQL server service
  service:
    name: mysqld
    state: started
    enabled: yes
  tags: [ mysql ]



# Manage tools, configuration, databases, accounts and backups
#
- import_tasks: root-password.yml
- import_tasks: mysqltuner.yml
- import_tasks: configuration.yml
- import_tasks: databases.yml
- import_tasks: backup.yml
