# Install required packages for compiling Git from source
#
- name: Install required packages for compiling Git
  dnf:
    name: [autoconf, expat-devel, gcc, gettext-devel, libcurl-devel, openssl-devel, perl-devel, zlib-devel, tar]
    state: latest
    enablerepo: powertools
  tags: [git]



# Download and unpack sources
# Source code will be downloaded from GitHub releases:
# https://github.com/git/git/releases
#
- name: Download Git source code
  get_url:
    dest: "{{ git_sources_location }}"
    url: "https://github.com/git/git/archive/v{{ git_version }}.tar.gz"
  tags: [git]

- name: Unpack downloaded Git source code
  unarchive:
    src: "{{ git_sources_location }}/git-{{ git_version }}.tar.gz"
    dest: "{{ git_sources_location }}"
    owner: "{{ git_build_user }}"
    group: "{{ git_build_group }}"
    copy: no
    creates: "{{ git_sources_location }}/git-{{ git_version }}"
  tags: [git]



# Compile and install Git
# It will be compiled by using different user than root.
# Install operation  must be executed as sudo user
#
- name: Compile Git
  command: "{{ item }}"
  args:
    chdir: "{{ git_sources_location }}/git-{{ git_version }}"
  with_items:
    - make clean
    - make configure
    - "./configure --prefix={{ git_install_path }}"
    - make
  become: true
  become_user: "{{ git_build_user }}"
  tags: [git]

- name: Install compiled Git
  command: make install
  args:
    chdir: "{{ git_sources_location }}/git-{{ git_version }}"
  tags: [git]



# Remove downloaded sources after installation
#
- name: Cleanup downloaded sources
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ git_sources_location }}/git-{{ git_version }}.tar.gz"
    - "{{ git_sources_location }}/git-{{ git_version }}"
  tags: [git]



# Add Git executables to PATH
# It will fix the issue when git compiled from source can be overridden by git installed with dnf
#
- name: Add Git executables to $PATH
  template:
    src: git.sh.j2
    dest: /etc/profile.d/git.sh
    owner: root
    group: root
    mode: 0644
  tags: [git]
