# Make sure that following groups are available in the system
#
- name: Create groups
  group:
    name: "{{ item }}"
    state: present
  with_items: "{{ users_groups_to_create }}"
  tags: [users]
