# Make sure that following users are available in the system
#
- name: Create users
  user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    groups: "{{ item.groups }}"
    append: true
    state: present
  with_items: "{{ users_to_create }}"
  tags: [users]

# Create the SSH id_rsa key if it does not exist
#
- name: Check if private id_rsa key exists
  ansible.builtin.stat:
    path: "/home/{{ item.name }}/.ssh/id_rsa"
  with_items: "{{ users_to_create }}"
  register: users_ssh_private_key_presence
  tags: [users]

- name: Create SSH private key
  ansible.builtin.user:
    name: "{{ item.item.name }}"
    generate_ssh_key: true
    ssh_key_bits: 4096
  with_items: "{{ users_ssh_private_key_presence.results }}"
  when:
    - item.item.generate_ssh_key
    - item.stat.exists == false
  tags: [users]



# Configure authorized keys for the users
#
- name: Add authorized keys to users
  authorized_key:
    user: "{{ item.name }}"
    key: "{{ item.authorized_keys }}"
  with_items: "{{ users_to_create }}"
  tags: [users]
