# Version of MongoDB
mongodb_version: "7.0.0"

# MongoDB Configuration file
mongodb_config_file: /etc/mongod.conf

# MongoDB admin user password
mongodb_admin_password: "P9rbsTavEY2hjuUuALijKWiNnqEkdbVM"

# MongoDB backup user password
mongodb_backup_user_password: "r8xO;ki55zSoNeZSl7tTv67sYTJ"

# MongoDB bind address for connection and TLS setup
mongodb_host: mongo.local

# If set to true, mongodb_host value will be added to /etc/hosts file for 127.0.0.1
mongodb_is_local: true

# List of databases with users
mongodb_databases:
  example:
    user: example
    password: "O14inEDG948dEEg2zcREZB"
    roles:
      - readWrite
      - dbAdmin
    backup: yes

# Data for the self-signed certificate for TLS configuration.
mongodb_tls_csr:
  cn: "{{ mongodb_host }}"
  o: Default organization
  ou: Default organizational unit
