# Redis version to be installed
redis_version: "6.0.5"

# Location where redis should be installed
redis_install_path: /usr/local/redis

# Location of files for redis sources
redis_sources_path: /usr/src

# User that will build redis from sources
redis_build_user: developer

# Group of the build user
redis_build_group: developer

# Where redis should store database files
redis_database_dir: /var/lib/redis

# Directory where Redis should store logs
redis_logs_dir: /usr/local/redis/logs

# List of default secure config options for /usr/local/redis/redis.conf file
redis_default_configuration:
  bind: "127.0.0.1"
  port: "6379"
  daemonize: "no"
  supervised: "systemd"
  loglevel: "notice"
  logfile: "{{ redis_logs_dir }}/redis.log"
  requirepass: "a-rgU!Uf3H}ktBiizEVKA]yM^qDCUW3Un#iL_3A&tpUx=>Zk"
  dir: "{{ redis_database_dir }}"

# Custom user settings to be applied to /usr/local/redis/redis.conf file. Please refer to README.md in this role
redis_user_configuration: []
