# Redis version to be installed
redis_version: "7.0.8"

# Location where redis should be installed
redis_install_path: /usr/local/redis

# Location of files for redis sources
redis_sources_path: /usr/src

# User that will build redis from sources
redis_build_user: developer

# Group of the build user
redis_build_group: developer

# Where redis should store database files
redis_database_dir: /var/lib/redis

# Directory where Redis should store logs
redis_logs_dir: "{{ redis_install_path }}/logs"

# IP address for Redis
redis_bind: "127.0.0.1"

# List of default secure config options for /usr/local/redis/redis.conf file
redis_default_configuration:
  bind: "{{ redis_bind }}"
  port: "0"
  tls-port: "6379"
  daemonize: "no"
  supervised: "systemd"
  loglevel: "notice"
  logfile: "{{ redis_logs_dir }}/redis.log"
  requirepass: "a-rgU!Uf3H}ktBiizEVKA]yM^qDCUW3UniL_3A&tpUx=>Zk"
  dir: "{{ redis_database_dir }}"
  tls-cert-file: "{{ redis_install_path }}/tls/redis.crt"
  tls-key-file: "{{ redis_install_path }}/tls/redis.key"
  tls-ca-cert-file: "{{ redis_install_path }}/tls/ca.crt"
  tls-dh-params-file: "{{ redis_install_path }}/tls/redis.dh"

# Custom user settings to be applied to /usr/local/redis/redis.conf file. Please refer to README.md in this role
redis_user_configuration: []

# Value for maximum backlog in kernel net.core.somaxconn
redis_net_core_somaxconn: "1024"

# Value for overcommit_memory
redis_overcommit_memory: "1"

# Whether to disable or enable transparent huge pages on system boot
redis_disable_transparent_huge_pages: yes
