# Install/Update OpenSSL to desired version
# These tasks will be executed when
#  1. OpenSSL is not installed from within this role
#  2. OpenSSL is installed but not in desired version
#
- name: Check if OpenSSL is installed
  shell: "{{ openssl_install_path }}/bin/openssl version | awk '{print $2}'"
  args:
    warn: no
  ignore_errors: yes
  changed_when: false
  register: openssl_version_test
  tags: [openssl]

- include_tasks: install.yml
  when: "openssl_version_test.stdout != openssl_version"
  tags: [openssl]
