# Download and unpack sources for libzip required for zip files
# Source code will be downloaded from following page:
# https://libzip.org/
#
- name: Download libzip source code
  get_url:
    dest: "{{ php_sources_path }}"
    url: "https://libzip.org/download/libzip-{{ php_libzip_version }}.tar.gz"
  tags: [php]

- name: Unpack downloaded libzip source code
  unarchive:
    src: "{{ php_sources_path }}/libzip-{{ php_libzip_version }}.tar.gz"
    dest: "{{ php_sources_path }}"
    owner: "{{ php_build_user }}"
    group: "{{ php_build_group }}"
    copy: no
    creates: "{{ php_sources_path }}/libzip-{{ php_libzip_version }}"
  tags: [php]



# Compile and install libzip
# It will be compiled by using different user than root.
# Install operation must be executed as sudo user
#
- name: Compile libzip
  command: "cmake3 -DCMAKE_INSTALL_PREFIX=/usr CMakeLists.txt"
  args:
    chdir: "{{ php_sources_path }}/libzip-{{ php_libzip_version }}"
  become: true
  become_user: "{{ php_build_user }}"
  tags: [php]

- name: Install compiled libzip
  command: make install
  args:
    chdir: "{{ php_sources_path }}/libzip-{{ php_libzip_version }}"
  tags: [php]
